/*
 * IncFile1.h
 *
 * Created: 3/9/2018 6:04:58 PM
 *  Author: kmcarrin
 */ 

#ifndef NAND_TEST_H_
#define NAND_TEST_H_

#include "NAND_Flash.h"
#include "usb_start.h"

#define TEST_DATA_SIZE      (10240)  /* 5 pages (2048 * 5) */
#define NUM_TEST_BLOCKS     (5)      /* Number of blocks to write data to total. */

 /*************************************************************
 * STRINGS
 * ------------------------------------------------------------
 * These strings are used for input and output messages that
 * are printed to a PC console over serial connection.
 **************************************************************/ 
/*extern char WELCOME[31];
extern char GOODBYE[10];
extern char START_WRITE[22];
extern char DONE_WRITE[25];
extern char START_READ[22];
extern char DONE_READ[24];
extern char NEW_LINE; */

/*************************************************************
 * TEST DATA
 * ------------------------------------------------------------
 * This array contains test data that will be written to the 
 * flash device. The data was randomly generated by a script
 * before it was added to the array. The amount of data is
 * given by TEST_DATA_SIZE, which is adjustable. To make this 
 * data set larger or smaller, the value of TEST_DATA_SIZE must
 * be edited in the define above as well as in the script that
 * generates these values.
 **************************************************************/ 
extern uint8_t TEST_DATA[TEST_DATA_SIZE];

uint8_t nand_test_driver();

 /*************************************************************
 * FUNCTION: nand_test_load_data()
 * -----------------------------------------------------------
 * This function loads a page of data based on the PAGE_SIZE.
 * Data is taken from a static TEST_DATA array containing 
 * TEST_DATA_SIZE elements. The value of TEST_DATA_SIZE must
 * be greater than PAGE_SIZE.
 *************************************************************/ 
void nand_test_load_data(uint8_t page[], const int PAGE_SIZE);

#endif /* NAND_TEST_H_ */